// React.js Form Component
const ExampleForm = () => {
  return (
    <div className="example-form">
      <h1>Example Form</h1>
      <ListBox
        name="Arial"
        size="8.25"
        charset="0"
        weight="400"
        underline="0"
        italic="0"
        strikethrough="0"
      />
      <Timer interval={10} left={3300} top={1080} />
      <CommandButton
        caption="Get Info"
        name="Arial"
        size="8.25"
        charset="0"
        weight="400"
        underline="0"
        italic="0"
        strikethrough="0"
      />
      <TextBox
        name="Arial"
        size="8.25"
        charset="0"
        weight="400"
        underline="0"
        italic="0"
        strikethrough="0"
      />
      <ListBox
        name="Arial"
        size="8.25"
        charset="0"
        weight="400"
        underline="0"
        italic="0"
        strikethrough="0"
      />
      <Frame
        caption="Controls"
        name="Arial"
        size="8.25"
        charset="0"
        weight="400"
        underline="0"
        italic="0"
        strikethrough="0"
      >
        <Label
          alignment="2"
          caption="Enter Handle:"
          name="Arial"
          size="8.25"
          charset="0"
          weight="400"
          underline="0"
          italic="0"
          strikethrough="0"
        />
        <Label
          alignment="2"
          caption="0"
          name="Arial"
          size="8.25"
          charset="0"
          weight="400"
          underline="0"
          italic="0"
          strikethrough="0"
        />
        <Label
          alignment="2"
          caption="Window Over:"
          name="Arial"
          size="8.25"
          charset="0"
          weight="400"
          underline="0"
          italic="0"
          strikethrough="0"
        />
        <Label
          alignment="2"
          caption="Children"
          name="Arial"
          size="8.25"
          charset="0"
          weight="400"
          underline="0"
          italic="0"
          strikethrough="0"
        />
        <Label
          alignment="2"
          caption="Siblings"
          name="Arial"
          size="8.25"
          charset="0"
          weight="400"
          underline="0"
          italic="0"
          strikethrough="0"
        />
      </Frame>
    </div>
  );
};